# Default database configuration
development:
  adapter: mysql
  host: localhost
  database: masti_development
  username: root
  password: 
  timeout: 5000

test:
  adapter: mysql
  host: localhost
  database: masti_test
  username: root
  password: 
  timeout: 5000

production:
  adapter: mysql
  host: localhost
  database: masti_production
  username: root
  password: 
  timeout: 5000

                                    
# special mode for demo.spreecommerce.com (you probably don't need this)                                    
#demo:
#  adapter: sqlite3
#  database: db/production.sqlite3
